### ISSUE TITLE
Suggestion for Switching Node Type

### ISSUE THREAD

**Issue by bischofftep** [AiSatan/node_wrangler_octane#1]
Hello, and thank you for this excellent modification to the Add-On!

Would you consider modifying the "Switch Node Type" menu of Node Wrangler to list only Octane Blender node types?

**Comment by AiSatan** [comment]
Hello and thank you!

I will try for sure, but I never use this one, can you help me out and tell me if this is the result you are expecting? 
I can add all octane nodes like this, not sure if all of them will be in on this custom "octane" menu or in different sub menus. 

Please check this out:

[https://youtu.be/p9yEwqwRFV8](https://youtu.be/p9yEwqwRFV8)

**Comment by AiSatan** [comment]
I make this build downloadable from this branch/link, you can try it by yourself. Only one node yet just to be sure.

[https://github.com/AiSatan/node_wrangler_octane/blob/switch_type_to/node_wrangler_octane.py](https://github.com/AiSatan/node_wrangler_octane/blob/switch_type_to/node_wrangler_octane.py)

**Comment by bischofftep** [comment]
Works great! Thank you!

Some possibilities that you might consider adding that aren't already in another plug-in (namely the Octane Helper):
ColorRamp -> Gradient Tex (might be a little tricker than just a "switch" but would be a HUGE help)
ImageTex <-> Float Image Tex (converting an RGB to a grayscale image tex, should be pretty straightforward I think?)

Those are the first two I could think of, I'm sure there are others that are similar and could be made to work but those I use all the time.

**Comment by AiSatan** [comment]
oh, this delay.
Please check out latest from the link above, I think I added all of them but can be bugs/not all.
And nodes name not very "friendly", but I hope they are understandable.

I tried to check out ColorRamp/ImageTex, but can't say yet if I can do something here
