### ISSUE TITLE
[Feature request] Bump+normal, gamma correction

### ISSUE THREAD

**Issue by nate-brs** [AiSatan/node_wrangler_octane#14]
Hi! First of all, this addon is super helpful, amazing work.
I'd like to know if it would be possible to add both bump and normal maps in the shader setup when both files are selected.
~~And another minor feature, would it be possible to automatically change the gamma to 1.0 for all non-color related maps? (This does the same thing as selecting Non-Color Data in Cycles)~~

Thanks!

Edit: just saw the closed issue about making non-color maps Image Float Tex, please disregard my second request

**Comment by AiSatan** [comment]
Hi, I'm glad it helps you!
I'll take a look, but can you provide a screenshot of the final setup you want to get, to be sure if I get it right and we are on the same node.

**Comment by nate-brs** [comment]
Sure! Here it is:
![image](https://user-images.githubusercontent.com/60856369/133764065-dd116164-1e36-441d-b1b7-5606148c4105.png)

For now when both maps are selected, only the bump gets imported and connects to the normal input of the Universal, which is wrong

**Comment by AiSatan** [comment]
Great, thanks!

Please try this version from this branch:

https://github.com/AiSatan/node_wrangler_octane/blob/%2314_bump_setup/node_wrangler_octane.py
(go to raw > save as > install in blender as usual)

Let me know if it works as you expected and I'll merge it to the master, thanks!

**Comment by nate-brs** [comment]
Thanks, that's perfect, it works as expected!
Very minor detail that doesn't necessarily have to be corrected (just letting you know), when both maps are imported their connections cross before entering the Universal. But again, it's only cosmetics and doesn't affect the functionality whatsoever.
![image](https://user-images.githubusercontent.com/60856369/133924372-b148c609-0cd2-464a-acd5-2a0e47bc70e0.png)

Thanks again, this addon is such a time saver!

**Comment by AiSatan** [comment]
Ah, I see, thanks!
I will fix this and make a new release.
Please, be free to create another issue if you have something in mind :)

**Comment by nate-brs** [comment]
Perfect, thank you so much :)
