### ISSUE TITLE
I have some problems using Blender 3.0 

### ISSUE THREAD

**Issue by Kinchan-1** [AiSatan/node_wrangler_octane#19]
sorry,In octane v.25.0 (Blender3.0), pressing ctrl+shift+left-click the shader does not respond and cannot be output to the material node.Thanks

**Comment by Kinchan-1** [comment]
hallo,Excuse me

**Comment by AiSatan** [comment]
Hi, thanks for letting me know, please try this new patch:

https://github.com/AiSatan/node_wrangler_octane/releases/tag/1.1

**Comment by AiSatan** [comment]
Please, let me know if it's work / not work, I will try to make more changes tomorrow.

**Comment by Kinchan-1** [comment]
Hello, thank you, I just tried the shader and it works, but there is a problem, except for the image texture, other nodes are output nodes directly.

**Comment by AiSatan** [comment]
Please, try this one

https://github.com/AiSatan/node_wrangler_octane/releases/tag/1.1.1

**Comment by AiSatan** [comment]
If you feel like nothing is changed, try to remove addon first and install again, can be an issue

**Comment by Kinchan-1** [comment]
This works, thank you very much

**Comment by AiSatan** [comment]
Happy to help, be free to let me know if you have any issues again, have a great day!
