### ISSUE TITLE
Octane Noise Texture Node doesnt display

### ISSUE THREAD

**Issue by Askaen** [AiSatan/node_wrangler_octane#24]
Hey in the latest release Ctrl+Shift+Clicking Noise Texture plugs it directly to Surface slot in Material Output Node. Thanks for the amazing work you are doing with this plugin tho keep it up!

**Comment by AiSatan** [comment]
Hi, thanks for letting me know, try this one, should be fixed

https://github.com/AiSatan/node_wrangler_octane/releases/tag/1.1.3

**Comment by Askaen** [comment]
Its fixed now thank you very much keep up the good work!
