### ISSUE TITLE
Errors on creating image setup 

### ISSUE THREAD

**Issue by izDimitri** [AiSatan/node_wrangler_octane#26]
No clue what is causing these errors:
[Ctrl+T](https://i.imgur.com/TDvUYxF.png)
[Viewer Node](https://i.imgur.com/jYGKvNE.png)

Shift+Ctrl+T shows a popup icon that says Select Shader node,
even though the Universal Material is set up.

Default Node wrangler Disabled

**Comment by AiSatan** [comment]
Hi, 
Sadly, I can't reproduce any of this.

By errors, it's seems like octane's plugin didn't register own shaders, not sure what could cause that.

You could try disable/enable octane plugin.
Which version of octane blender do you use? I tested only with 24.5 and 25.0, you could try them.
Perhaps, good old reinstalling octane blender could help as well.

Let me know if it's not getting away, we'll figure it out.

**Comment by izDimitri** [comment]
Ah, seems I was out of date with the version,
Reinstalling with the newer version fixed the problem.
Thanks for the info.
