### ISSUE TITLE
Alt + R to reload images 

### ISSUE THREAD

**Issue by vdawg-git** [AiSatan/node_wrangler_octane#28]
When pressing Alt + R to reload all images in the node tree I always get this error., even though I do have images to reload.
`No images found to reload in this node tree`

This is a really useful command for packaging design, since I can quickly update my 3D render with the changes I did in Illustrator.

Please fix it, and thank you a lot for creating and maintaining this plugin fork :)

**Comment by AiSatan** [comment]
Hi, thanks!

I fixed that, but seems like Octane have an issue on it's own and sadly I can't do anything about it. 

https://render.otoy.com/forum/viewtopic.php?f=114&t=74918

I had to make small hack to go around this issue and force update, but you should be aware of it:

after you click alt+r - all nodes will changes bit-rate of images to opposite (16bit to 32bit or 32bit to 16bit), if you click alt+r again, they will switch back. Some pictures to be more clear, English hard. Except this, it should work just fine, but please let me know if I missed something, thanks!

![image](https://user-images.githubusercontent.com/2905049/163026763-2ec58248-06cf-4bcb-a7fc-06500a662f3f.png)
![image](https://user-images.githubusercontent.com/2905049/163026798-6020ce9f-7d43-4178-b24e-72e3d9cc3e32.png)



Please try this build, and let me know if it's ok for you:

https://github.com/AiSatan/node_wrangler_octane/blob/develop/node_wrangler_octane.py

**Comment by AiSatan** [comment]
https://github.com/AiSatan/node_wrangler_octane/releases/tag/1.1.4

**Comment by vdawg-git** [comment]
It works! (Pressing twice is nessecary, but that is fairly easy to do :) )
