### ISSUE TITLE
trowing error on linux making the addon unable to load

### ISSUE THREAD

**Issue by matsaa93** [AiSatan/node_wrangler_octane#30]
the plugin sends an error making it not load do to it calling a windows only library(from asyncio.windows_events import NULL) as a import.
line: from asyncio.windows_events import NULL
needs to be enclosed with an if statment checking for active the OS is Windows, or be commented out in a separate release for linux.
the addon works fine under linux after i commented that line out, or at least to the point i have used it.

**Comment by AiSatan** [comment]
Hi, thanks for letting me know!

I added check for windows, Linux version of blender indeed doesn't contain this line. Sadly, I can't test it myself, please let me know if this helped:

https://github.com/AiSatan/node_wrangler_octane/releases/tag/1.1.5

**Comment by matsaa93** [comment]
it is working without any problems.
