### ISSUE TITLE
Preview node doesn't work in Blender Octane 2021.5 26.3

### ISSUE THREAD

**Issue by Yurimo16** [AiSatan/node_wrangler_octane#32]
Hi, 

Thank you so much for this addon. Couldn't use octane without it.
The node preview doesn't work in Octane 2021.5 26.3.

Will appreciate any help

Yuri

**Comment by AiSatan** [comment]
Hi, glad to hear and thanks for letting me know!
Seems like they changed shaders once again, it'll take a little time to update, but I'll let you know here, thanks!

**Comment by AiSatan** [comment]
Hm, no, it seems working for me, I hope you understood you right, viewer and "add texture setup" working for me with the stable 26.3: https://render.otoy.com/forum/viewtopic.php?f=113&t=79938

please check if you:
- disabled default node wrangler 
![image](https://user-images.githubusercontent.com/2905049/182841999-68c07062-f108-4171-b9b5-04b3f8c8858d.png)

- using latest from here: https://github.com/AiSatan/node_wrangler_octane/releases
- renderer set to 'octane' - 
![image](https://user-images.githubusercontent.com/2905049/182841891-9a479d16-76a8-4579-8b7e-7d194f54ac0c.png)


should be fine:

https://user-images.githubusercontent.com/2905049/182841506-f9b2ddbf-6d90-480a-b304-d65cf7484826.mp4

**Comment by Yurimo16** [comment]
Seems I didn't installed the plugin correctly. It is working now! 
Thank you, appreciate your help!

**Comment by AiSatan** [comment]
Glad to hear, be free to let me know if you face any issue again, have a nice day! :)
