### ISSUE TITLE
Alt+shift rmb connects nodes incorrectly

### ISSUE THREAD

**Issue by igrbessonov** [AiSatan/node_wrangler_octane#34]
Hey man!
First of all, thank you very much for your work.
I have a problem when I use alt+shift rmb to connect texture with universal material. The nodes connect incorrectly. For example, if I want to connect noise and transparency in this way, i get a connection texture with the Medium slot. Maybe I'm doing something wrong. 
Thanks again)

**Comment by AiSatan** [comment]
Hi, thanks for letting me know!
Can you try with the latest from here and confirm if it helped? 
Please, check with multiple node to be sure, but let me know if you will face any issues, thanks!

https://github.com/AiSatan/node_wrangler_octane/releases

**Comment by igrbessonov** [comment]
WOW, man!
I didn't even expect you to answer me at all. But what you fixed in such a short time is just crazy. Now everything works great! I am very grateful to you. Your addon makes my life easier every day. Cheers
