### ISSUE TITLE
Node wrangler for Octane 2021.1.6 26.5

### ISSUE THREAD

**Issue by Yurimo16** [AiSatan/node_wrangler_octane#40]
Hello,

Just installed the new octane version 26.5 and node wrangler 1.2.0 and the node preview doesn't work.
Any help and support is highly appreciated.

Thank you,
Yuri

**Comment by AiSatan** [comment]
Hi,

Can you share any screenshot with error and more details, like which node or all of them?, I'll take a look

You should also try:
- remove and install it again
- check if default node wrangler is disabled

**Comment by Yurimo16** [comment]
Hi,
Thank you for the reply
I tried reinstalling it and checked that the default node wrangler is disabled. Still no node preview. 
I don't see any error message just the CTRL+ SHIFT+ LMB don't work to preview any node texture for example.
Did you tried it with the new Octane version?

**Comment by AiSatan** [comment]
Yeah, I just reinstalled 26.5 and recorded this, can you please check if versions you see in the video the same for you and if blender's console show any messages like this? 
it'll be great if you could also test default node wrangler behavior, does it work for you with cycle?

hopefully quality good enough to see texts

https://www.youtube.com/watch?v=IpqkkDAJErk

**Comment by Yurimo16** [comment]
The version looks the same
![image](https://user-images.githubusercontent.com/110605347/196040068-21843c55-cd1c-4e5d-bd6b-611c281d4b54.png)
![image](https://user-images.githubusercontent.com/110605347/196040281-57ecf774-824e-492e-a6af-0a0673ad58db.png)

I tasted as you with image texture and it works but not for procedural textures
![image](https://user-images.githubusercontent.com/110605347/196040233-2e52d1e9-9471-47ea-8657-113a2ba16bcc.png)

**Comment by AiSatan** [comment]
This is great! Let me fix that and I'll be back with new version, a moment

**Comment by AiSatan** [comment]
Please, try the last one, it would be great if you leave confirmation commend here and I'll close this, but be free to create a new one if you have any new issues!

https://github.com/AiSatan/node_wrangler_octane/releases

**Comment by Yurimo16** [comment]
Thank you so much! Works with any texture now!
