### ISSUE TITLE
viewer error

### ISSUE THREAD

**Issue by se0zzae** [AiSatan/node_wrangler_octane#46]
![화면 캡처 2023-10-10 102651](https://github.com/AiSatan/node_wrangler_octane/assets/147458462/9f6f4daf-4178-4e8a-b4ff-ac32679d71ee)
[](url)

I don't know much about computer language. Please help me

**Comment by AiSatan** [comment]
Hi, can you try one of this versions and see it helpes?
Please remove installed version first

https://github.com/AiSatan/node_wrangler_octane/releases/tag/1.3.0

https://github.com/AiSatan/node_wrangler_octane/releases/tag/1.2.2

**Comment by AiSatan** [comment]
hopefully it helped, I will close this now, but feel free to re-open or create a new one if you have any problems, thanks :)

**Comment by se0zzae** [comment]
I'm using the latest version of the blender, and using version 1.2.2 solved
the problem. Thank you so much!

2023년 10월 10일 (화) 오후 12:48, AiSatan ***@***.***>님이 작성:
