### ISSUE TITLE
Problem with viewer node

### ISSUE THREAD

**Issue by 99toy** [AiSatan/node_wrangler_octane#48]
Hello, first of all thank you for work!

My issue is: when I try to use Ctrl+Shift+click on a node, blender says: Error: Python: Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\node_wrangler_octane.py", line 1690, in invoke
    return self.invoke_octane(context, event)
  File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\node_wrangler_octane.py", line 1552, in invoke_octane
    output_types = [x.nodetype for x in
TypeError: 'NoneType' object is not iterable

Maybe It's only my problem but I don't know how to solve it. Ctrl+T and other comands works well.

thank you in advance

**Comment by AiSatan** [comment]
Hi, someone had similar issue before, can you please check if 1.2.2 version resolve it for you?

https://github.com/AiSatan/node_wrangler_octane/releases/tag/1.2.2

Full disscussion is here #46, but be free to let me know, thanks!

**Comment by AiSatan** [comment]
Hopefully it worked for you, I'll close this issue but be free to reopen it / create one if you face any issues, thanks!
