### ISSUE TITLE
Alpha and transmission not supported and roughness issue

### ISSUE THREAD

**Issue by Ekkiwnox** [AiSatan/node_wrangler_octane#49]
Hello I hope you're doing well,

I've just noticed that alpha maps are not supported yet. Any possible way to include it in the addon? Same for transmission. (CTRL+SHIFT+T)
I've also noticed that there's an extra RGB between the roughness map and the universal node. Any idea why? (CTRL+SHIFT+T)

Thank you so much for your amazing work :-)
Camille

**Comment by AiSatan** [comment]
Hi, Cameille
I'm glad you liked it! 

I'll take a look at this and return to you with answers /a new version, as asap as possible :) 

Meanwhile, it'll be very helpful if you let me know your plugin and blender & octane version, so I can check with it, after I make my fixes, it'll save us both some time, thanks!

**Comment by Ekkiwnox** [comment]
Hello AiSatan,
Hope you're doing well :-)

I'm running Octane Studio+ 2022.1.1 with Blender 3.5.1 on Windows 11 :-)
I tried to update to the last version of Octane Studio, but they have some major issues with some nodes :-)
Thanks in advance, 
Camille

**Comment by AiSatan** [comment]
Ok, thanks! :)

> I've just noticed that alpha maps are not supported yet. Any possible way to include it in the addon? Same for transmission. (CTRL+SHIFT+T)

I made a new release, please try it out, and feel free to leave a feedback here / reopen the issue / create a new issue in the future, happy to help :)

https://github.com/AiSatan/node_wrangler_octane/releases

> I've also noticed that there's an extra RGB between the roughness map and the universal node. Any idea why? (CTRL+SHIFT+T)

I'm not sure how it works exactly, but basically it's for roughness maps if they are actually gloss map.
It's seems related to metalness/specular workflow, but i'm not 100% sure of a details, but default node_wrangler does that, and I have to do it as well I guess, here some link to related answer:
https://www.reddit.com/r/blender/comments/6alro8/glossy_map_invert/

But, it shouldn't be just RGB node, I replaced this behavior with "invert" checkbox on the roughtness texture node. So, if roughtness image actually gloss map, it would be inverted.

But, if you don't want this behavior, I also attached custom build just for you :)

**Don't forget to extract the file before installing**

[node_wrangler_octane 1_4_0_Camille.zip](https://github.com/AiSatan/node_wrangler_octane/files/13587397/node_wrangler_octane.1_4_0_Camille.zip)

 In the future, if you want manually change default behavior, you can use this simple instructions:

- open file with notepad or anything for text
- find this code in file, you can use cntr+F hotkey and search for "texture_node.inputs["Invert"].default_value = True" you should find just one result.
- you'll see this code (or pretty similar to this one):

```python
                    if match_rough:
                        # If Roughness nothing to to
                        link = links.new(active_node.inputs[sname[0]], texture_node.outputs[0])

                    elif match_gloss:
                        link = links.new(active_node.inputs[sname[0]], texture_node.outputs[0])
                        texture_node.inputs["Invert"].default_value = True

                else:
                    # This is a simple connection Texture --> Input slot
                    link = links.new(active_node.inputs[sname[0]], texture_node.outputs[0])

```

- just change texture_node.inputs["Invert"].default_value = True to False, and it will look like this

```python

                    if match_rough:
                        # If Roughness nothing to to
                        link = links.new(active_node.inputs[sname[0]], texture_node.outputs[0])

                    elif match_gloss:
                        link = links.new(active_node.inputs[sname[0]], texture_node.outputs[0])
                        texture_node.inputs["Invert"].default_value = False

                else:
                    # This is a simple connection Texture --> Input slot
                    link = links.new(active_node.inputs[sname[0]], texture_node.outputs[0])


```

- And you done! Install the addon and it should work withhout it :)

feel free to let me know, if you face any issues with this :)

**Comment by Ekkiwnox** [comment]
Hello :-)
Thank you so much, will try everything this weekend :-)
I would let you know how it goes :-)
Thank you so much again

**Comment by Ekkiwnox** [comment]
Hey I just wanted to say a HUGE thank you :-) The add-on works perfectly :-)
Honestly, you should maintain this add-on and put it on the Blender market, I'm pretty people would love to buy it and support you :-)

Thank you again, it's truly life changer :-)

**Comment by AiSatan** [comment]
It's great to hear that it works! :) Please feel free to let me know if it ever stops working. I'll do my best to help.

I'll try to put it out there for free to give more people access to it, but money isn't my passion :)

If there is any money to spare, it's best to support Blender itself. I bet they would spend it much better than I :D

Thank you! <3
