### ISSUE TITLE
"principled texture set up"

### ISSUE THREAD

**Issue by AlexPearce3D** [AiSatan/node_wrangler_octane#5]
First of all, thank you for this add-on, it's awesome! 

I create an add-on called AP Octane, and I have users who've asked me for some things, that you've already taken care of, so I am sending people this way to find your add-on. 

Someone asked me if I could basically do the "Principled Texture Set up", but I thought I would see if you could build it into your add-on, it would make more sense there. 

Just like in node wrangler, that feature would basically take images that you've selected, search their name and if it contains '_basecolor' in the file name it connects it to Albedo color in the Universal Material, etc. 

Thanks again! 

![image](https://user-images.githubusercontent.com/16144863/113972136-f7c7a900-97ee-11eb-9a58-9abe244ef1cc.png)

**Comment by AiSatan** [comment]
Hi, I'm glad you liked it!

Yes, I'm planning on adding it, moreover I'll push first version that is working with "universal shader" later today. I'll link this issue so you'll be notified as well.
If you or someone from your community can help with testing it, it'll great!
I'm not 100% sure how to use some of the textures+nodes with octane, so any feedback will be appreciated.

**Comment by AiSatan** [comment]
https://www.youtube.com/watch?v=IMk_W-4pnnA

**Comment by AlexPearce3D** [comment]
Very cool!

Yes I can share it in my discord and ask for people to beta test and give
feedback. Is it already pushed to your github?

Are you apart of the fb group for octane for blender?

I can also share it there and it's a great resource for learning about
octane.




Alex Pearce
Director, Immersive Technology
888.510.0497 x708

Swivel Creative
318 W Adams St. | Suite 1200A | Chicago, IL 60606
http://www.swivelcreative.com

www.linkedin.com/in/AlexPearceXR/

This email and any files transmitted with it are for the sole use of the
intended recipient(s) and may contain confidential and privileged
information. Any unauthorized use of this email is strictly prohibited.
©2019 Swivel Creative. All rights reserved.

**Comment by AiSatan** [comment]
It would be great, thanks!

No, I'm not part of fb at all, if you could please be free to share it with people/community where's it can be helpful.

it's not in the master branch yet, but I made this release link, to easy download it, you can share it so people can test:

https://github.com/AiSatan/node_wrangler_octane/releases/tag/0.4

**Comment by AlexPearce3D** [comment]
Awesome!
Alex Pearce
Director, Immersive Technology
SwivelCreative.com

On April 8, 2021 at 15:11 GMT, AiSatan ***@***.***> wrote:

It would be great, thanks!

No, I'm not part of fb at all, if you could please be free to share it with people/community where's it can be helpful.

it's not in the master branch yet, but I made this release link, to easy download it, you can share it so people can test:

https://github.com/AiSatan/node_wrangler_octane/releases/tag/0.4

**Comment by AiSatan** [comment]
Hi, I will push latest changes and close this issue, but feel free to open a new one if you have  any new suggestion/bugs/etc.
a video example of the latest will be available shortly here:
https://youtu.be/SON0bUczSf0

to get latest version please go here and use latest stable one:

https://github.com/AiSatan/node_wrangler_octane/releases

**Comment by AlexPearce3D** [comment]
Thanks! Glad you joined the fb group. I haven't been able to test it but one of my friends said they tested it and it worked great.
Alex Pearce
Director, Immersive Technology
SwivelCreative.com

On April 10, 2021 at 10:06 GMT, AiSatan ***@***.***> wrote:

Closed [#5](https://github.com/AiSatan/node_wrangler_octane/issues/5) via [#6](https://github.com/AiSatan/node_wrangler_octane/pull/6).
