### ISSUE TITLE
 blender 4.0.2 is not supported yet

### ISSUE THREAD

**Issue by Jackbrobeep** [AiSatan/node_wrangler_octane#51]
blender 4.0.2 is not supported yet（octaneblender addon V28.7）
![image](https://github.com/AiSatan/node_wrangler_octane/assets/136829587/cea513fa-d8ca-4f1d-9383-42156f243a69)

**Comment by AiSatan** [comment]
Hi,
Thanks for letting me know, I'll take a look and comeback to you, thanks!

**Comment by Jackbrobeep** [comment]
Thank you, this plug-in is very useful and has helped me a lot

AiSatan ***@***.***> 于2023年12月14日周四 08:25写道：

**Comment by AiSatan** [comment]
I'm glad to hear that!

I made a bug fix for you, you can download 1.4.1 now, 

https://github.com/AiSatan/node_wrangler_octane/releases

Please, feel free to let me know if it works for you, and/or if you face any issues in the future, just create a new issue, I'll do my best to help! :)

Thank you!

**Comment by Jackbrobeep** [comment]
Cool, it works perfectly, thank you for your input. I have a request, I
wonder if you have time to make an add-on for octane like this?
[image: 654210463f48d323ccd088bbf87df16.png]

AiSatan ***@***.***> 于2023年12月15日周五 01:43写道：
