### ISSUE TITLE
Can't use with cycles

### ISSUE THREAD

**Issue by Bmendess** [AiSatan/node_wrangler_octane#56]
Hi, 

I'm trying to use your addon it works great but I have to keep switching to the original Node Wrangler when I need to use cycles... its supposed to be like that or it shoud work in both renderers?

I'm using the latest version of octane render and the latest version of your addon

![image](https://github.com/AiSatan/node_wrangler_octane/assets/43620995/21f7e3eb-fb34-4263-8a80-bec870caaaf9)

**Comment by AiSatan** [comment]
Hi, 

It should work with both, but seems like last changes broke something. 

Can you please try this 1.5.0 version instead

Installation:

- Download the zip file below
- Remove old node_wrangler_octane (or/and disable default one)
- **Restart Blender** -- very important
- Install this **zip file** (this time it'll be zip, new node_wrangler changed their code, so I have to follow)
- Just in case double check if version is 1.5.0 now in Blender
- Try everything you usually use, let me know, thanks!

[node_wrangler_octane.zip](https://github.com/AiSatan/node_wrangler_octane/files/14026768/node_wrangler_octane.zip)

If everything working fine for you, you can just keep using it, I'll release this 1.5.0 as soon as I fix "mix" feature, but it can take some time.

If you encounter any issues at all, be free to let me know, I'll try to fix this for you as asap as possible, thanks!

**Comment by Bmendess** [comment]
Perfect now! Thanks! Amazing work man

**Comment by AiSatan** [comment]
Great, I'll close this for now, but feel free to reopen/create a new one if you have some issues

Thanks, Enjoy :)
