### ISSUE TITLE
Was adjusting some code untill i found yours

### ISSUE THREAD

**Issue by schroef** [AiSatan/node_wrangler_octane#58]
Hi there,

i bumped into this video about Octane for Blender and thought i try it. Than heard the guy say sadly Node Wrangler doesnt work. But found out it just some small parts which dont work. I was wondering why they do a visibility check for hidden, enabled and CUSTOM. 

Do you know why they specifically check for CUSTOM in is_visible_socket()

Just checked your code and i see the function is still there in the operator.py. I did not check how you can get passed that. My idea was to simply add a custom check if engine is on "OCTANE_Render"

**Comment by AiSatan** [comment]
Hi,

I'm not entirely certain, but I believe a check for CUSTOM in is_visible_socket was added around nw v3.40, which is around the time Blender was adding geometry nodes. Most likely, this check is related to that. But it also could be just a bug fix for custom nodes made by users/plugins.

My fix might not look the best (it should be an elif statement with "in"), but it works ([link to the code](https://github.com/AiSatan/node_wrangler_octane/blob/5903bd07f65d12f064adf373c3b1b16044e5a5db/node_wrangler_octane/operators.py#L753)):

```python
                            if is_visible_socket(out):
                                valid = True
                                break
                            elif active.outputs[0].name == "Material out":
                                valid = True
                                oct_valid = True
                                break
                            elif active.outputs[0].name == "Texture out":
                                valid = True
                                oct_valid = True
                                break
```

For the engine check, I simply do:

 ```python
   if context.scene.render.engine == 'octane':	
            return self.invoke_octane(context, event)
```

This is related to the fact that I really want to keep the original methods untouched to ensure they work with Eevee/Cycles.

I hope I answered your question, but feel free to ask more :)

Also, please feel free to fork/merge this code with yours or send me pull requests if you feel like it. Thanks!
